name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Installer Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Autoriser Gradle
      run: chmod +x ./gradlew

    - name: Compiler APK
      run: ./gradlew assembleDebug

    - name: Récupérer l'APK
      uses: actions/upload-artifact@v4
      with:
        name: QuizDepartementsFrance-APK
        path: app/build/outputs/apk/debug/app-debug.apk
